version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    ports:
        - "27037:27017"
    volumes:
        - mongo_data:/data/db
  
  basketdb:
    container_name: basketdb
    ports:
        - "63791:6379"    

  discountdb:
    container_name: discountdb
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin1234
        - POSTGRES_DB=DiscountDb
    ports:
        - "54321:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data/
  
  portainer:
    container_name: portainer
    ports:
        - "8800:8000"
        - "9900:9000"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8001:80" 

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
    depends_on:
        - basketdb
    ports:
      - "8002:80"


  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
        - discountdb
    ports:
      - "8003:80"

